server:
  port: 8400
spring:
  application:
    name: caller-server



# 开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true

  client:
    config:
      default:
        connectTimeout: 5000  # 指定Feign连接提供者的超时时限


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9601/eureka/
  instance:
    ip-address: ${spring.cloud.client.ip-address}
    hostname: ${eureka.instance.ip-address}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
