server:
  port: 8001
spring:
  application:
    name: provider-server


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9601/eureka/
  instance:
    ip-address: ${spring.cloud.client.ip-address}
    hostname: ${eureka.instance.ip-address}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
